package com.kwdevs.hospitalsdashboard.views.assets

val years = listOf( "2025","2026","2027","2028","2029","2030",
    "2031","2032","2033","2034","2035","2036",
    "2037","2038","2039","2040","2041","2042",
    "2043","2044","2045","2046","2047","2048",
    "2049","2050","2051","2052","2053","2054",
    "2055","2056","2057","2058","2059","2060")
val months= listOf("1","2","3","4","5","6","7","8","9","10","11","12")
val days= listOf("1","2","3","4","5","6","7","8","9","10","11","12",
    "13","14","15","16","17","18","19","20","21","22","23","24",
    "25","26","27","28","29","30","31")

fun monthName(month:String?): String {
    return when(month){
        "1"->"يناير"
        "2"->"فبراير"
        "3"->"مارس"
        "4"->"ابريل"
        "5"->"مايو"
        "6"->"يونيو"
        "7"->"يوليو"
        "8"->"اغسطس"
        "9"->"سبتمبر"
        "10"->"اكتوبر"
        "11"->"نوفمبر"
        "12"->"ديسمبر"
        else->EMPTY_STRING
    }
}
//A
const val ADD_MULTIPLE_ITEMS_LABEL              =   "اضغط هنا للإضافة,\n يمكنك إضافة اكثر من صنف"
const val AREA_LABEL                            =   "الحى"
const val ACTIVE_LABEL                          =   "فعال"
const val ACCOUNT_TYPE_LABEL                    =   "نوع الحساب"
const val ADD_NEW_LABEL                         =   "إدخال جديد"
const val ACTION_TYPE_LABEL                     =   "العملية"
const val ADD_NEW_USER_LABEL                    =   "إضافة مستخدم جديد"
const val ADD_NEW_TABLE_LABEL                   =   "إضافة جدول جديد"
const val ADD_NEW_SUPER_USER_LABEL              =   "إضافة مستخدم مميز جديد"
const val ADD_NEW_ROLE_LABEL                    =   "إضافة دور جديد"
const val ADD_NEW_PERMISSION_LABEL              =   "إضافة صلاحية جديدة"
const val ADD_NEW_CONDITION_LABEL               =   "إضافة شرط جديد"
const val ADD_NEW_HOSPITAL_DEVICE_LABEL         =   "إضافة جهاز جديد"
const val ADMISSIONS_LABEL                      =   "الدخول"
const val AT_6_AM_LABEL                         =   "06 صباحا"
const val AT_12_PM_LABEL                        =   "12 ظهرا"
const val AT_6_PM_LABEL                         =   "06 مساءا"
const val APHERESIS_LABEL                       =   "فصل دم"
const val APHERESIS_DONORS_LABEL                =   "عدد متبرعين فصل الدم"

//B
const val BURNS_CU_LABEL                        =   "رعاية الحروق"
const val BACK_TO_MAIN_LABEL                    =   "العودة للرئيسية"
const val BACK_TO_HOSPITALS_LABEL               =   "العودة لقائمة المستشفيات"
const val BED_CODE_LABEL                        =   "رقم السرير"
const val BIRTHS_LABEL                          =   "الولادات"
const val BABY_DIED_LABEL                       =   "وفاة الطفل"
const val BIRTH_TYPE_LABEL                      =   "نوع الولادة"
const val BIRTHDATE_LABEL                       =   "تاريخ الولادة"
const val BEDS_COUNT_LABEL                      =   "عدد الأسرة"
const val BLOOD_BANK_LABEL                      =   "بنك الدم"
const val BLOOD_GROUP_LABEL                     =   "الفصيلة"
const val BLOOD_UNITS_LABEL                     =   "وحدات دم"
const val BY_CITY_LABEL                         =   "حسب المحافظة"
const val BY_AREA_LABEL                         =   "حسب الحى"
const val BY_DIRECTORATE_LABEL                  =   "حسب المديرية"
const val BY_SECTOR_LABEL                       =   "حسب القطاع"
const val BY_TYPE_LABEL                         =   "حسب التصنيف"
const val BY_PATIENT_LABEL                      =   "بواسطة المريض"
const val BLOOD_STOCK_LABEL                     =   "مخزون الدم"

//C
const val CAMPAIGNS_LABEL                       =   "حملات"
const val CURRENT_PERCENT_LABEL                 =   "النسبة الحالية"
const val CAMPAIGN_CODE_LABEL                   =   "كود الحملة"
const val CCU_LABEL                             =   "رعاية القلب"
const val CITY_LABEL                            =   "المدينة"
const val SECTOR_LABEL                          =   "القطاع"
const val CREATE_NEW_HOSPITAL_LABEL             =   "إدخال بيانات مستشفى جديدة"
const val CANCEL_LABEL                          =   "إلغاء"
const val CLOSE_LABEL                           =   "إغلاق"
const val CHANGES_SAVED_LABEL                   =   "تم حفظ التغييرات بنجاح"
const val COLUMNS_NAME_LABEL                    =   "اسماء العمدان"
const val CONDITIONS_LABEL                      =   "الشروط"
const val COLUMN_NAME_LABEL                     =   "اسم العامود"
const val CODE_LABEL                            =   "الكود"
const val CLINICS_LABEL                         =   "العيادات"
const val CESAREAN_LABEL                        =   "قيصرى"
const val CANCER_CURE_LABEL                     =   "علاج الكيماوى"
const val CSP_LABEL                             =   "بلازما منزوعة الكرايو"
const val CRAYO_LABEL                           =   "كرايو"
const val CAMPAIGN_LABEL                        =   "الحملة"
const val CAMPAIGN_LOCATION_LABEL               =   "مكان الحملة"
const val CAMPAIGN_TYPE_LABEL                   =   "نوع الحملة"
const val COLLECTION_LABEL                      =   "التجميع"
const val CAMPAIGN_DATE_LABEL                   =   "تاريخ الحملة"
//D
const val DAILY_BLOOD_COLLECTION_LABEL          =   "التجميع اليومى"
const val DETAILED_FILTER_LABEL                 =   "تصفية تفصيلية"
const val DETAILED_DATA_LABEL                   =   "بيانات تفصيلية"
const val DEPARTMENTS_LABEL                     =   "الأقسام"
const val DELETE_LABEL                          =   "حذف"
const val DIRECTORATE_LABEL                     =   "المديرية"
const val DIRECTORATES_LABEL                    =   "المديريات"

const val DONATION_TYPE_LABEL                   =   "نوع التبرع"
const val DEVICE_STATUS_LABEL                   =   "حالة الجهاز العامة"
const val DEVICE_TYPE_LABEL                     =   "نوع الجهاز"
const val DAY_LABEL                             =   "اليوم"
const val DEPARTMENT_LABEL                      =   "القسم"
const val DEVICES_LABEL                         =   "الاجهزة"
const val DEPARTMENT_DEPUTY_LABEL               =   "نائب رئيس القسم"
const val DEPARTMENT_HEAD_LABEL                 =   "رئيس القسم"
const val DIE_PATIENT_LABEL                     =   "وفاة المريض"
const val DEATH_DATE_LABEL                      =   "تاريخ الوفاة"
const val DATA_SAVED_LABEL                      =   "تم الحفظ بنجاح"
const val DONE_LABEL                            =   "تمت"
const val DATE_LABEL                            =   "التاريخ"
const val DEATHS_COUNT_LABEL                    =   "الوفيات"
const val DAILY_BLOOD_STOCK_UPDATE_LABEL        =   "تعديل مخزون الدم اليومى"
const val DEPARTMENT_COMPONENT_LABEL            =   "قسم المشتقات"
const val DEPARTMENT_SEROLOGY_LABEL             =   "قسم السيرولوجى"
const val DEPARTMENT_ISSUING_LABEL              =   "قسم الصرف"
const val DEPARTMENT_DONATION_LABEL             =   "قسم التبرع"
const val DAILY_PROCESSING_REPORTS_LABEL        =   "تقارير فصل الدم اليومية"
const val DAILY_PROCESSING_LABEL                =   "فصل الدم"
const val DEPARTMENT_THERAPEUTIC_LABEL          =   "الوحدة العلاجيه"
const val DELETE_PATIENT_LABEL                  =   "حذف بيانات مريض"
const val DATA_LOADED_LABEL                     =   "تم استيراد البيانات بنجاح"
//E
const val EMPTY_STRING                          =   ""
const val EMERGENCY_STOCK_LABEL                 =   "طواريء"
const val EXPIRY_DATE_LABEL                     =   "تاريخ انتهاء الصلاحية"
const val ERROR_COLLECTION_DATE_REQUIRED_LABEL  =   "تاريخ التبرع مطلوب"
const val ERROR_RE_LOGIN_LABEL                  =   "من فضلك اعد تسجيل الدخول"
const val ERROR_UNIT_TYPE_FIELD_REQUIRED_LABEL  =   "نوع المشتق مطلوب"
const val ERROR_DONATION_TYPE_REQUIRED_LABEL    =   "نوع التبرع مطلوب"
const val ERROR_CAMPAIGN_TYPE_REQUIRED_LABEL    =   "نوع الحملة مطلوب"
const val ERROR_TOTAL_COLLECTION_REQUIRED_LABEL =   "اجمالى التبرع مطلوب"
const val ERROR_CAMPAIGN_CODE_REQUIRED_LABEL    =   "كود الحملة مطلوب"
const val ERROR_APHERESIS_DONORS_REQUIRED_LABEL =   "عدد متبرعين الفصل مطلوب"
const val ERROR_DATE_ENTRY_MISSING_LABEL        =   "بعض البيانات المطلوبة, غير مدخلة"
const val ERROR_NAME_FILED_REQUIRED_LABEL       =   "الاسم مطلوب"
const val ERROR_ADDRESS_FIELD_REQUIRED_LABEL    =   "العنوان مطلوب"
const val ERROR_CITY_FIELD_REQUIRED_LABEL       =   "المدينة مطلوبة"
const val ERROR_AREA_FIELD_REQUIRED_LABEL       =   "الحى/القرية مطلوب"
const val ERROR_SECTOR_FIELD_REQUIRED_LABEL     =   "القطاع مطلوب"
const val ERROR_TYPE_FIELD_REQUIRED_LABEL       =   "التصنيف مطلوب"
const val ERROR_LOADING_DATA_LABEL              =   "لا يمكن استيراد البيانات في الوقت الحالى"
const val ERROR_CREATING_DATA_LABEL             =   "لا يمكن حفظ البيانات في الوقت الحالى"
const val EMPLOYEES_LABEL                       =   "العاملين"
const val EMPLOYEE_LABEL                        =   "موظف"
const val EDIT_TABLE_LABEL                      =   "تعديل جدول"
const val EDIT_LABEL                            =   "تعديل"
const val EDIT_PATIENT_DATA_LABEL               =   "تعديل بيانات المريض"

const val ENTER_DATE_LABEL                      =   "تاريخ الدخول:"
const val EXIT_DATE_LABEL                       =   "تاريخ الخروج:"
const val EXIT_TIME_LABEL                       =   "وقت الخروج"
const val EXIT_LABEL                            =   "خروج"
const val EXPORTS_LABEL                         =   "الصادرات"
//F
const val FOLLOWS_LABEL                         =   "تابعة لـ"
const val FILTER_LABEL                          =   "تصفية"
const val FILTER_BY_CAMPAIGN_CODE_LABEL         =   "تصفية بكود الحملة"
const val FREE_UNITS_LABEL                      =   "الوحدات المتاحة"
const val FIRST_NAME_LABEL                      =   "الاسم الأول"
const val FATHER_NAME_LABEL                     =   "اسم الأب"
const val FOURTH_NAME_LABEL                     =   "الاسم الرابع"
const val FROM_LABEL                            =   "من"
const val FOR_LABEL                             =   "الى"
const val FEMALE_LABEL                          =   "انثى"
const val FFP_LABEL                             =   "بلازما طازجة"
const val FP_LABEL                              =   "بلازما مجمدة"

//G
const val GENERAL_CU_LABEL                      =   "الرعايات"
const val GRAND_FATHER_NAME_LABEL               =   "اسم الجد"
const val GENDER_LABEL                          =   "النوع"
const val GOVERNMENTAL_LABEL                    =   "حكومى"

//H
const val HOSPITAL_TYPE_LABEL                   =   "التصنيف"
const val HAS_ICU_DEPARTMENTS_LABEL             =   "بها اقسام رعاية"
const val HAS_ICU_LABEL                         =   "بها غرف رعاية مركزة"
const val HAS_CCU_LABEL                         =   "بها غرف رعاية قلب"
const val HAS_NEUROLOGY_CU_LABEL                =   "بها غرف رعاية مخ واعصاب"
const val HAS_BURNS_CU_LABEL                    =   "بها غرف رعاية حروق"
const val HAS_ONCOLOGY_CU_LABEL                 =   "بها غرف رعاية اورام"
const val HAS_NICU_LABEL                        =   "بها غرف رعاية اطفال"
const val HAS_MORGUE_LABEL                      =   "بها ثلاجات حفظ الموتى"
const val HAS_DEVICES_LABEL                     =   "بها اجهزة"
const val HAS_DEPARTMENTS_LABEL                 =   "بها اقسام"
const val HAS_WARDS_LABEL                       =   "بها غرف داخلى"
const val HAS_RENAL_DEVICES_LABEL               =   "بها اجهزة غسيل كلوى"
const val HOME_LABEL                            =   "الرئيسية"
const val HOSPITAL_LABEL                        =   "المستشفى"
const val HOSPITALS_LABEL                       =   "مستشفيات"
const val HOSPITAL_NAME_LABEL                   =   "اسم المستشفى"
const val HOSPITAL_ADDRESS_LABEL                =   "عنوان المستشفى"

//I
const val INCINERATION_REASON_LABEL             =   "سبب الإعدام"
const val INCINERATION_BLOOD_LABEL              =   "إعدام دم"
const val INCINERATION_INFO_LABEL               =   "تفاصيل الإعدامات"
const val IN_CITY_LABEL                         =   "بمدينة"
const val IN_AREA_LABEL                         =   "بحى/منطقة"
const val IN_PATIENT_LABEL                      =   "الداخلى"
const val ICU_LABEL                             =   "الرعاية المركزة"
const val IN_PATIENT_ONE_LABEL                  =   "غرفة داخلى"
const val IN_PATIENT_MULTIPLE_LABEL             =   "غرف داخلى"
const val IN_ACTIVE_LABEL                       =   "غير فعال"
const val INCUBATORS_LABEL                      =   "الحضانات"
const val INFANT_NAME_LABEL                     =   "اسم الطفل"
const val INFANT_NATIONAL_ID_LABEL              =   "رقم هوية الطفل"
const val INCINERATION_LABEL                    =   "الإعدامات"
const val IS_PRIVATE_SECTOR_LABEL               =   "م/قطاع خاص"
const val IS_NBTS_LABEL                         =   "خ.ن.د.ق"
const val INSERT_AT_LEAST_ONE_ITEM_LABEL        =   "أدخل صنف واحد على الأقل"
const val IMPORTS_LABEL                         =   "الواردات"

//J

//K
const val KPI_LABEL                             =   "مؤشرات الأداء"

//L
const val LOADING_LABEL                         =   "جارى تحميل البيانات.."
const val LOGIN_LABEL                           =   "سجل دخول"
const val LAB_TESTS_LABEL                       =   "التحاليل"
const val LOG_LABEL                             =   "السجل"
const val LOGIN_FIRST_FIRST_LABEL               =   "من فضلك سجل دخول اولا"
const val LOAD_DATA_LABEL                       =   "تحميل البيانات"

//M
const val MAX_PERCENT_LABEL                     =   "اقصى نسبة"
const val MIN_FREE_BEDS_LABEL                   =   "اقل عدد اسرة متاحة"
const val MAX_FREE_BEDS_LABEL                   =   "اقصي عدد اسرة متاحة"
const val MAIN_DATA_LABEL                       =   "البيانات الاساسية"
const val MORGUE_LABEL                          =   "المشرحة"
const val MEDICAL_DEPARTMENTS_LABEL             =   "اقسام طبية"
const val MEDICAL_DEVICE_LABEL                  =   "جهاز طبى"
const val MOBILE_NUMBER_LABEL                   =   "رقم الموبايل"
const val ALTERNATIVE_MOBILE_NUMBER_LABEL       =   "رقم موبايل آخر "
const val MAJOR_LABEL                           =   "كبرى"
const val MINOR_LABEL                           =   "صغرى"
const val MALE_LABEL                            =   "ذكر"
const val MOTHER_DIED_LABEL                     =   "وفاة الأم"
const val MOTHER_NAME_LABEL                     =   "اسم الأم"
const val MONTH_LABEL                           =   "شهر"
const val MONTH_FROM_LABEL                      =   "من شهر"
const val MONTH_TO_LABEL                        =   "الى شهر"
const val MEDICAL_EXAMINATIONS_FREQUENCY_LABEL  = "معدل الكشوفات"
const val MOTHER_NATIONAL_ID_LABEL              =   "رقم هوية الأم"
const val MIDNIGHT_LABEL                        =   "منتصف الليل"
const val MONTHLY_REPORTS_LABEL                 =   "تقارير شهرية"
const val MISSING_BLOOD_GROUP_DATA              =   "بعض بيانات الدم غير موجودة"
const val MISSING_PLASMA_DATA                   =   "بعض بيانات البلازما غير موجودة"

//N
const val NEW_INCINERATION_ITEM_LABEL           =   "إعدام وحدات"
const val NO_DATA_LABEL                         =   "لا يوجد بيانات"
const val NAME_LABEL                            =   "الاسم"
const val NICU_LABEL                            =   "رعاية الأطفال"
const val NEUROLOGY_CU_LABEL                    =   "رعاية المخ والاعصاب"
const val NATIONALITY_LABEL                     =   "الجنسية"
const val NATIONAL_ID_LABEL                     =   "رقم الهوية"
const val NEW_ADMISSION_LABEL                   =   "تسجيل دخول مريض جديد"
const val NEW_WARD_LABEL                        =   "عنبر مرضى جديد"
const val NEW_OPERATION_ROOMS_LABEL             =   "غرفة عمليات جديدة"
const val NEW_OPERATION_LABEL                   =   "عملية جديدة"
const val NEW_MORGUE_LABEL                      =    "جديد للمشرحة"
const val NORMAL_LABEL                          =   "طبيعى"
const val NEW_RENAL_WASH_LABEL                  =   "جلسة غسيل جديدة"
const val NEW_USAGE_FREQUENCY_LABEL             =   "معدل استخدام جديد"
const val NEW_PATIENT_LABEL                     =   "إضافة مريض جديد"
const val NEW_IMPORT_LABEL                      =   "وارد جديد"
const val NEAR_EXPIRED_LABEL                    =   "قارب على الانتهاء"
const val NOTE_LABEL                            =   "ملحوظة"
const val UNITS_NUMBER_LABEL                    =   "عدد الوحدات"
//O
const val OF_TYPE_LABEL                         =   "تصنيفها"
const val ONCOLOGY_CU_LABEL                     =   "رعاية الأورام"
const val OPERATIONS_LABEL                      =   "العمليات"
const val OPERATION_TIME_LABEL                  =   "وقت دخول العملية"
const val OPERATIONS_LIST_LABEL                 =   "قائمة العمليات"
const val ONLY_STREET_OR_PLANNED_CAMPAIGNS      =   "فقط للحملات المنظمة او الميدانية"
const val OPERATION_ROOMS_LABEL                 =   "غرف العمليات"
const val OPERATION_ROOM_LABEL                  =   "غرفة العمليات"

const val OPERATION_TYPE_LABEL                  =   "نوع العملية"
const val OPERATION_RUNNING_LABEL               =   "مازال في العمليات"
const val OPERATION_STATUS_LABEL                =   "حالة العملية"
const val OUT_PATIENT_LABEL                     =   "خارجى"
const val OK_LABEL                              =   "حسنا"
const val OTHER_HOSPITAL_LABEL                  =   "مستشفيات اخرى"
//P
const val PLANNED_LABEL                         =   "منظم"
const val PROCESSING_DATE_LABEL                 =   "تاريخ الفصل"
const val PERCENT_LABEL                         =   "النسبة"
const val PLASMA_LABEL                          =   "بلازما"
const val PASSWORD_LABEL                        =   "كلمة المرور"
const val PREVIEW_LABEL                         =   "المعاية"
const val PERMISSIONS_LABEL                     =   "الصلاحيات"
const val PATIENTS_LABEL                        =   "المرضى"
const val PATIENT_QUIT_LABEL                    =   "خروج"
const val PATIENT_CODE_LABEL                    =   "كود المريض"
const val PATIENT_HAS_QUIT_LABEL                =   "خرج"
const val PATIENT_IS_PRESENT_LABEL              =   "بالمستشفى"
const val PATIENT_DIE_LABEL                     =   "وفاة"
const val PRETERM_LABEL                         =   "المبتسرين"
const val PHYSICAL_THERAPY_LABEL                =   "العلاج الطبيعى"
const val PATIENTS_FILTER_PROMPT_LABEL          =   "يمكنك البحث فقط عن المرضى الذين تم تسجيل دخولهم الى المستشفى"
const val PATIENT_LABEL                         =   "المريض"
const val PATIENT_DATA_LABEL                    =   "بيانات المريض"
const val PACKED_RBCS_LABEL                     =   "دم مكدس"
const val PRIVATE_LABEL                         =   "خاص"
const val DATE_FROM_LABEL                       =   "اول تاريح"
const val DATE_TO_LABEL                         =   "اخر تاريخ"
//Q
const val QUIT_PATIENT_LABEL                    =   "خروج المريض"
const val QUANTITY_LABEL                        =   "الكمية"

//R
const val RANDOM_DONOR_PLATELETS_LABEL          =   "صفائح دموية (متبرع عشوائى)"

const val RENAL_DEVICE_LABEL                    =   "جهاز غسيل الكلى"
const val RENAL_DEVICES_LABEL                   =   "اجهزة غسيل الكلى"
const val RESTORE_LABEL                         =   "استعادة"
const val RESTORE_PATIENT_LABEL                 =   "استعادة بيانات مريض"
const val ROLES_LABEL                           =   "الادوار"
const val ROLE_LABEL                            =   "الدور"
const val RENAL_WASH_DEVICE_LABEL               =   "جهاز غسيل كلوى"
const val RENAL_WASH_SESSIONS_FREQUENCY_LABEL   =   "جلسات الغسيل"
const val RECEPTION_LABEL                       =   "الاستقبال"
const val RECIPIENT_LABEL                       =   "المستلم"
const val RECIPIENT_TYPE_LABEL                  =   "نوع المستلم"

//S
const val SPACE                                 =   " "
const val STREET_LABEL                          =   "شارع"
const val STATUS_LABEL                          =   "الحالة"
const val SEARCH_BY_CAMPAIGN_CODE               =   "بحث بكود الحملة"
const val SECTORS_LABEL                         =   "القطاعات"
const val SELECT_CITY_LABEL                     =   "اختر المدينة"
const val SELECT_STATUS_LABEL                   =   "اختر الحالة"
const val SELECT_HOSPITAL_TYPE_LABEL            =   "اختر نوع المستشفى"
const val SELECT_SECTOR_LABEL                   =   "اختر القطاع"
const val SELECT_TYPE_LABEL                     =   "اختر التصنيف"
const val SELECT_NATIONALITY_LABEL              =   "اختر الجنسية"
const val SELECT_GENDER_LABEL                   =   "اختر النوع"
const val SCAN_ID_LABEL                         =   "مسح البطاقة"
const val SELECT_BIRTH_TYPE_LABEL               =   "اختر نوع الولادة"
const val SELECT_CLINIC_LABEL                   =   "اختار العيادة"
const val SELECT_TABLE_LABEL                    =   "اختر الجدول"
const val SELECT_ACTION_TYPE_LABEL              =   "اختر نوع العملية"
const val SELECT_DEVICE_STATUS_LABEL            =   "اختر حالة الجهاز العامة"
const val SELECT_DEVICE_TYPE_LABEL              =   "اختر نوع الجهاز"
const val SELECT_DEPARTMENT_LABEL               =   "اختر القسم"
const val SELECT_AREA_LABEL                     =   "اختر الحى"
const val SELECT_ROLE_LABEL                     =   "اختر الدور"
const val SELECT_REASON_LABEL                   =   "إختر سبب"
const val SELECT_PERMISSION_LABEL               =   "اختر الصلاحية"
const val SELECT_PROCESSING_DATE_LABEL          =   "اختر تاريخ الفصل"
const val SELECT_UNIT_SOURCE_LABEL              =   "اختر مصدر الوحدات"
const val SELECT_ACCOUNT_TYPE                   =   "اختر نوع الحساب"
const val SELECT_TITLE_LABEL                    =   "اختر المسمى الوظيفي"
const val SELECT_BLOOD_BANK_LABEL               =   "اختر بنك الدم"
const val SELECT_CAMPAIGN_LABEL                 =   "اختر الحملة"
const val SELECT_HOSPITAL_LABEL                 =   "اختر المستشفى"
const val SEE_ALL_LABEL                         =   "مشاهدة الكل.."
const val SELECT_DATE_LABEL                     =   "اختر التاريج"
const val SELECT_RECIPIENT_LABEL                =   "اختر المستلم"
const val SPECIAL_NAME_LABEL                    =   "اسم مخصص"
const val SAVE_CHANGES_LABEL                    =   "حفظ التغييرات"
const val SLUG_LABEL                            =   "اسم الرابط المبسط"
const val SHOW_DATE_TIME_PICKER_LABEL           =   "اختار التاريخ/الوقت"
const val SHOW_ENTER_DATE_PICKER_LABEL          =   "تاريخ الدخول"
const val SHOW_BIRTHDATE_PICKER_LABEL           =   "تاريخ الولادة"
const val SHOW_EXIT_DATE_PICKER_LABEL           =   "تاريخ الخروج"
const val SELECT_DEPARTMENT_TYPE_LABEL          =   "اختر القسم"
const val SELECT_PATIENT_STATE_LABEL            =   "اختر حالة المريض"
const val SELECT_OPERATION_TYPE_LABEL           =   "اختر نوع العملية"
const val SELECT_OPERATION_ROOM_LABEL           =   "اختر غرفة العمليات"
const val SELECT_OPERATION_STATUS_LABEL         =   "اختر حالة العملية"
const val SELECT_UNIT_TYPE_LABEL                =   "اختر المشتق"
const val SELECT_DEATH_DATE_LABEL               =   "ادخل تاريخ الوفاة"
const val SELECT_BLOOD_GROUP_LABEL              =   "اختر الفصيلة"
const val SESSIONS_LABEL                        =  "جلسات"
const val SHOW_WARDS                            =   "إظهار الغرف"
const val SELECT_EXAMINATION_TYPE_LABEL         =   "اختر نوع الكشف"
const val SAVE_PROMPT                           =   "هل انت متأكد انك تريد حفظ هذه التغييرات؟"
const val SELECT_TIME_LABEL                     =   "اختر الوقت"
const val SELECT_LABEL                          =   "اختر"
const val STOCK_LABEL                           =   "المخزون"
const val STRATEGIC_LABEL                       =   "استراتيجى"
const val SINGLE_DONOR_PLATELETS_LABEL          =   "صفائح دموية (متبرع واحد)"

//T
const val TO_LABEL                              =   "الى"
const val TOTAL_LABEL                           =   "الاجمالى"
const val TOTAL_INCINERATED_ITEMS               =   "إجمالى وحدات الإعدام"
const val TOTAL_PROCESSED_LABEL                 =   "إجمالى الفصل"
const val TOTAL_UNITS_LABEL                     =   "إجمالى الوحدات"
const val TOTAL_OPERATIONS_LABEL                =   "إجمالى العمليات"
const val TOTAL_OPERATIONS_THIS_MONTH_LABEL     =   "إجمالى العمليات هذا الشهر"
const val TUMORS_LABEL                          =   "الأورام"
const val TRY_AGAIN_LATER_LABEL                 =   "حاول في وقت لاحق"
const val TABLES_LABEL                          =   "الجداول"
const val TABLE_LABEL                           =   "الجدول"
const val TIME_LABEL                            =   "الوقت"
const val TITLE_LABEL                           =   "المسمى الوظيفي"
const val TRANSFER_PATIENT_LABEL                =   "نقل المريض"
const val THIS_MONTH_LABEL                      =   "هذا الشهر"
const val THIS_HOSPITAL_LABEL                   =   "هذه المستشفى"

//U
const val USERNAME_LABEL                        =   "اسم المستخدم"
const val USER_CONTROL_HEADER_LABEL             =   "صفحة إدارة المستخدمين"
const val USAGE_FREQUENCY_LABEL                 =   "معدل الاستخدام"
const val UNDER_INSPECTION_LABEL                =   "تحت الفحص"
const val UNIT_TYPE_LABEL                       =   "نوع المشتق"
const val UNIT_LABEL                            =   "وحدة"
const val UPDATE_PATIENT_LABEL                  =   "تعديل بيانات مريض"
const val UNIT_SOURCE_LABEL                     =   "مصدر الوحدة"
//V
const val VIEW_LABEL                            =   "تفاصيل"

//W
const val WELCOME_USER_LABEL                    =   "اهلا بك,"
const val WHERE_EN_LABEL                        =   "where"
const val WHERE_IN_EN_LABEL                     =   "whereIn"
const val WHERE_OR_EN_LABEL                     =   "orWhere"
const val WARDS_LABEL                           =   "الاقسام الداخلية"
const val NEXT_DESTINATION_LABEL                =   "ما هى وجهتك التالية؟"
const val WHOLE_BLOOD_LABEL                     =   "دم كامل"

//X

//Y
const val YEAR_LABEL                            =   "السنة"
const val YEAR_FROM_LABEL                       =   "من سنة"
const val YEAR_TO_LABEL                         =   "الى سنة"

//Z
